name: productpulse
version: '1.0.0'
config-version: 2
profile: productpulse
model-paths: ["models"]
models:
  productpulse:
    staging:
      +materialized: incremental
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts
